### ISSUE TITLE
您好!高并发的情况下不停的出现failed to connect to all addresses

### ISSUE THREAD

**Issue by yilongmd** [CreditTone/mitmproxy-hub#1]
Addon error: Traceback (most recent call last):
  File "D:\NetTools\PyMitmProxyHub\mitm_flow_callback.py", line 41, in request
    fixedMitmRequest = self.grpcClient.onMitmRequest(mitmRequest)
  File "D:\NetTools\PyMitmProxyHub\venv\lib\site-packages\grpc\_channel.py", line 923, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "D:\NetTools\PyMitmProxyHub\venv\lib\site-packages\grpc\_channel.py", line 826, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1612284521.156000000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":5391,"referenced_errors":[{"created":"@1612284519.626000000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":398,"grpc_status":14}]}"
>

Addon error: Traceback (most recent call last):
  File "D:\NetTools\PyMitmProxyHub\mitm_flow_callback.py", line 72, in response
    fixedMitmResponse = self.grpcClient.onMitmResponse(mitmResponse)
  File "D:\NetTools\PyMitmProxyHub\venv\lib\site-packages\grpc\_channel.py", line 923, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "D:\NetTools\PyMitmProxyHub\venv\lib\site-packages\grpc\_channel.py", line 826, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1612284521.161000000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":5391,"referenced_errors":[{"created":"@1612284519.626000000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":398,"grpc_status":14}]}"
>

**Comment by CreditTone** [comment]
参考下：https://stackoverflow.com/questions/59823424/grpc-14-unavailable-failed-to-connect-to-all-addresses
另外，希望不要用windows开发，程序员应该用mac。
